export const API_BASE = "https://v2.api.noroff.dev";
export const API_AUTH = "/auth";
export const API_REGISTER = "/register";
export const API_LOGIN = "/login";
export const API_KEY_URL = "/create-api-key";
export const API_POSTS = "/social/posts";
export const API_KEY = "f6b3f2fa-9202-4fa7-a38b-41e1f9b2b358";
export const API_QUERY_AUTHOR = "_author=true";
export const API_QUERY_COMMENT = "_comments=true";
export const API_PROFILE = "/social/profiles"